### ISSUE TITLE
HTTP downgrade

### ISSUE THREAD

**Issue by tie** [SebyakinAndrei/IHeardYouLikeLicense#2]
Shikimori работает исключительно по HTTPS.  Обычный пользователь ожидает end-to-end зашифрованное подключение для всех действий на сайте.  Расширение же отправляет запросы на HTTP сервис.

https://github.com/SebyakinAndrei/IHeardYouLikeLicense/blob/8fb68475be1e60db401b358f7de8bf7455971593/justice.js#L31

https://github.com/SebyakinAndrei/IHeardYouLikeLicense/blob/8fb68475be1e60db401b358f7de8bf7455971593/justice.js#L53

Предлагаю настроить получение сертификатов от *Let's Encrypt*.  Если нужно, то могу помочь с конфигурацией сервера.

ЗЫ: *Cloudflare* — зло.  Если у вас нет своего сертификата, то весь трафик все равно будет идти через Интернет без шифрования.  Разве что введете всех в заблуждение зелёным замочком.

**Comment by SebyakinAndrei** [comment]
Конечно можно, но какой в этом смысл? Максимум, что смогут сделать злоумышленники, это через Mitm заменить список серий, т.к насколько я понимаю, eval'ов туда не повставлять. Поэтому защищать-то тут и нечего.
Если правда есть желание этим заняться, то могу дать доступ к серверу по ssh, т.к у меня сейчас еще 2 текущих проекта и дел невпроворот. (в таком случае, лучше связаться со мной в [вк](https://vk.com/supersebyakin))
Спасибо за замечания)

**Comment by SebyakinAndrei** [comment]
> "Я скорее перепишу сервер на Go и добавлю в расширение возможность работать с несколькими серверами, чем притронусь к чужой конфигурации."

Прозвучало несколько оскорбительно...

Ну, надобность в нескольких серверах сейчас впринципе отсутствует. Сейчас у меня вся бд весит 26кб, а в одном запросе приходит инфа только по 1 эпизоду. Rps вообще никакой (сейчас 368 юзеров), так что что-то ускорять тут и в помине не нужно, а если и понадобится, просто прикручу ко всему этому делу memcached.

Ну, а насчет https, подумаю, если руки в ближайшее время дойдут, то, возможно, запилю.

**Comment by SebyakinAndrei** [comment]
Сейчас у меня главная проблема с дистрибьюцией всего этого. 
Если есть желание помочь, то главная проблема сейчас - неработоспособность расширения в firefox'е, т.к тот не поддерживает пересылку сообщений из background'а в content script через `chrome.tabs.sendRequest` (да и в хроме там она уже deprecated), так что нужно заменить это на более годную альтернативу.
Буду рад любой помощи)

**Comment by b1narykid** [comment]
>>"Я скорее перепишу сервер на Go и добавлю в расширение возможность работать с несколькими серверами, чем притронусь к чужой конфигурации."
>Прозвучало несколько оскорбительно

Простите, что так плохо выразился.  Проблема не в вашей конфигурации, а *моих* кривых руках и немного извращенных вкусах.

>проблема с дистрибьюцией всего этого

Завтра ~ухожу~ улетаю на отдых.  Там займусь этим, если будет время и доступ в Интернет.

**Comment by SebyakinAndrei** [comment]
Большое спасибо!)
