### ISSUE TITLE
Страница с эпизодами имеет два плеера

### ISSUE THREAD

**Issue by Andray1** [SebyakinAndrei/IHeardYouLikeLicense#20]
Приветствую. Заметил что в последнее время на сайте при просмотре эпизодов стало отображаться два плеера.
![image](https://user-images.githubusercontent.com/17046021/53289893-3ee4b280-37be-11e9-8155-a5fe08eecb5d.png)

**Comment by SebyakinAndrei** [comment]
Привет)
Да, есть такая тема, это из-за того, что из-за правок Морра, связанных с отображением лицензированных тайтлов, появилась такая штука. Я написал об этом в тред об ошибках, но пока вроде никакой реакции не поступало. Вприницпе, можно пофиксить на уровне расширения, не сильно большая проблема, если кто возьмется, будет круто. У меня времени пока не особо, к сожалению)

**Comment by SebyakinAndrei** [comment]
@Andray1 Все поправили в последнем релизе, issue закрываю)
