### ISSUE TITLE
Кривые width и height

### ISSUE THREAD

**Issue by VKartze** [SebyakinAndrei/IHeardYouLikeLicense#4]
Ну, уот такая хрень. На просмотр в фуллскрине не влияет, но выглядит не очень.
![655](https://user-images.githubusercontent.com/41291372/43831638-ffa425e6-9b2e-11e8-8e59-0da8523deddb.png)

**Comment by SebyakinAndrei** [comment]
Ну, width там задаётся контейнером, а height в расширении рассчитывается как половина viewport'а, соответственно на экранах с обычным соотношением сторон должно нормально работать. Если есть идея, как рассчитать height более правильно, буду рад ее выслушать)

**Comment by wakirin** [comment]
вроде обычно формат 16:9 ?
`_WIDTH_ * 9 / 16`

**Comment by VKartze** [comment]
думаю, нужно подсмотреть, как рассчитывается подобное в других плеерах. а так высота должна зависеть от ширины, в определенной пропорции. сейчас у меня никаких идей нема. закрою, пушто:
1) проблема не мешает выполнению основной функции;
2) размышляю над костылем.
